### ISSUE TITLE
Tags "not_requested" and "Requested_by" tagged to the same movies

### ISSUE THREAD

**Issue by Bokaii** [manybothans/plex-requester-collections#2]
I don't know what the script did, but seems the 2nd time it ran something went wrong and all the tags are weird:
![image](https://github.com/manybothans/plex-requester-collections/assets/10463748/4a4bc772-502f-4a22-ba00-c937ec1cae78)

After the first run I also had "requester_watched" tags, but they disappeared  after the 2nd run

**Comment by manybothans** [comment]
Hey, I caught this issue over the weekend and put out a fix already. It _should_ fix itself next time it runs with the latest version, or you could batch-edit the media items in plex/radarr/sonarr to remove all tags just to be sure, then run the latest version (v1.2.0).

**Comment by manybothans** [comment]
Please lmk if this doesn't work and I'll re-open the issue.
